### ISSUE TITLE
Debian Buster with Raspberry Pi Desktop

### ISSUE THREAD

**Issue by tlkw79** [rlancaste/AstroPi3#12]
Hi,

which script that I can use on this Debian Buster with Raspberry Pi Desktop? 

Regards,
Tom

**Comment by rlancaste** [comment]
Hi Tom,

I think that the setupDebianSBC.sh would be the appropriate one.  To be honest though, the original astropi3 script and the raspbian one are now the most developed ones.  I was working on the Debian one and the Manjaro one, but I ran out of time at the end of the summer and I'm not sure they are as refined as the others.  But it should still work pretty well.  

Thanks,

Rob

**Comment by tlkw79** [comment]
Hi Rob,

This Debian Buster with Raspberry Pi Desktop is still in x86 state. Is Kstars compatible with it? Actually i tried once with the setupDebianSBC.sh, but until the INDI and Kstars installation stage, a lot of errors and some not be able to pass thru.. :( So, I stop it. 

Thanks,
Tom

**Comment by rlancaste** [comment]
Hi Tom,

Gotcha, well if there are errors in the KStars build, then I don't think that is something I can fix in the script.  That being said, I would be surprised if it couldn't build on an x86 system.  One question, you said it has Raspberry Pi Desktop, is this essentially an installation of Raspbian, or do you just have the desktop?  So would the Raspbian Script run?

Thanks,

Rob

**Comment by rlancaste** [comment]
Did this work out ok?

**Comment by tlkw79** [comment]
Actually no. I choose another linux distro. Sorry about that. I will now close this issue without any testing.
