### ISSUE TITLE
Error setupAstroRaspbianPi.sh

### ISSUE THREAD

**Issue by Dragonball1472** [rlancaste/AstroPi3#19]
As I run the Raspbian script, I couldn't run the scripts in the folder "utilities". Also I can't couldn't found INDI, PHD2 and KStars.

**Comment by rlancaste** [comment]
That sounds like the script did not complete?  Did you get any errors while running the script?

**Comment by Dragonball1472** [comment]
Ok I flasched the SD card again, wrote sudo apt-get update and sudo get-apt full-upgrade and run the script.

Here is the text from the script:

pi@raspberrypi:~ $ sudo apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.20.1-2+deb10u3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ git clone https://github.com/rlancaste/AstroPi3.git
Cloning into 'AstroPi3'...
remote: Enumerating objects: 1196, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 1196 (delta 73), reused 68 (delta 30), pack-reused 1079
Receiving objects: 100% (1196/1196), 5.08 MiB | 3.54 MiB/s, done.
Resolving deltas: 100% (781/781), done.
pi@raspberrypi:~ $ cd AstroPi3
pi@raspberrypi:~/AstroPi3 $ sudo ./setupAstroRaspbianPi.sh
You are running BASH 5.0.3(1)-release as the root user.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Welcome to the AstroPi3 Raspberry Pi 3 or 4 Raspbian KStars/INDI Configuration Script.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ This will update, install and configure your Raspberry Pi 3 or 4 to work with INDI and KStars to be a hub for Astrophotography. Be sure to read the script first to see what it does and to customize it.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Are you ready to proceed (y/n)? y

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Testing connections to required web addresses for running the script.  If the pi cannot connect to the internet, you should correct this before running the script.  If a required resource is not available, you should find out if the resource has moved, or remove the requirement for this resource.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ZRam-script was found. The script can proceed.
INDI-Git-Repo was found. The script can proceed.
INDI-3rdparty-Repo was found. The script can proceed.
GSC-Source was found. The script can proceed.
StellarSolver-Repo was found. The script can proceed.
KStars-Repo was found. The script can proceed.
PHD2-Repo was found. The script can proceed.
WX-FormBuilder-Repo was found. The script can proceed.
PHD2-LogViewer-Repo was found. The script can proceed.
INDIWebManagerApp-Repo was found. The script can proceed.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Checking items that will require your input while running the script, so you don't get asked so many questions later.  Note that some installations later (VNC, samba in particular) may still require your input later on, this is out of my control.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Do you want to give your pi a static ip address so that you can connect to it in the observing field with no router or wifi and just an ethernet cable (y/n)? y
Please enter the IP address you would prefer.  Please make sure that the first two numbers match your client computer's self assigned IP.  For Example mine is: 169.254.0.5 ? 
***********
IP Address is in correct format, proceeding
Do you wish to configure the field wifi hotspot to automatically come up after a certain time if there is no wifi network (y/n)? n

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Updating installed packages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done                              
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Setting desktop icons to open programs when you click them.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Setting account: pi to auto login.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Setting HDMI settings in /boot/config.txt.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Installing Synaptic
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcairo-perl libept1.5.0 libglib-perl libgtk2-perl libpango-perl
  libxapian30
Suggested packages:
  libfont-freetype-perl libgtk2-perl-doc xapian-tools dwww menu deborphan
  apt-xapian-index software-properties-gtk
The following NEW packages will be installed:
  libcairo-perl libept1.5.0 libglib-perl libgtk2-perl libpango-perl
  libxapian30 synaptic
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,196 kB of archives.
After this operation, 14.7 MB of additional disk space will be used.
Get:1 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libcairo-perl armhf 1.106-3+b1 [84.9 kB]
Get:2 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libxapian30 armhf 1.4.11-1 [959 kB]
Get:3 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libept1.5.0 armhf 1.1+nmu3+b1 [77.7 kB]
Get:4 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libglib-perl armhf 3:1.329-1 [329 kB]
Get:5 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libpango-perl armhf 1.227-3+b1 [150 kB]
Get:6 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libgtk2-perl armhf 2:1.24992-1+b2 [576 kB]
Get:7 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf synaptic armhf 0.84.6+rpi1 [2,020 kB]
Fetched 4,196 kB in 2s (2,113 kB/s)   
Selecting previously unselected package libcairo-perl.
(Reading database ... 163690 files and directories currently installed.)
Preparing to unpack .../0-libcairo-perl_1.106-3+b1_armhf.deb ...
Unpacking libcairo-perl (1.106-3+b1) ...
Selecting previously unselected package libxapian30:armhf.
Preparing to unpack .../1-libxapian30_1.4.11-1_armhf.deb ...
Unpacking libxapian30:armhf (1.4.11-1) ...
Selecting previously unselected package libept1.5.0:armhf.
Preparing to unpack .../2-libept1.5.0_1.1+nmu3+b1_armhf.deb ...
Unpacking libept1.5.0:armhf (1.1+nmu3+b1) ...
Selecting previously unselected package libglib-perl.
Preparing to unpack .../3-libglib-perl_3%3a1.329-1_armhf.deb ...
Unpacking libglib-perl (3:1.329-1) ...
Selecting previously unselected package libpango-perl.
Preparing to unpack .../4-libpango-perl_1.227-3+b1_armhf.deb ...
Unpacking libpango-perl (1.227-3+b1) ...
Selecting previously unselected package libgtk2-perl.
Preparing to unpack .../5-libgtk2-perl_2%3a1.24992-1+b2_armhf.deb ...
Unpacking libgtk2-perl (2:1.24992-1+b2) ...
Selecting previously unselected package synaptic.
Preparing to unpack .../6-synaptic_0.84.6+rpi1_armhf.deb ...
Unpacking synaptic (0.84.6+rpi1) ...
Setting up libxapian30:armhf (1.4.11-1) ...
Setting up libglib-perl (3:1.329-1) ...
Setting up libept1.5.0:armhf (1.1+nmu3+b1) ...
Setting up libcairo-perl (1.106-3+b1) ...
Setting up libpango-perl (1.227-3+b1) ...
Setting up synaptic (0.84.6+rpi1) ...
Setting up libgtk2-perl (2:1.24992-1+b2) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for desktop-file-utils (0.23-4) ...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Enabling SSH
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssh-server is already the newest version (1:7.9p1-10+deb10u2+rpt1).
openssh-server set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh
Created symlink /etc/systemd/system/sshd.service -> /lib/systemd/system/ssh.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ssh.service -> /lib/systemd/system/ssh.service.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  dns-root-data dnsmasq-base gcr gnome-keyring gnome-keyring-pkcs11
  libayatana-appindicator3-1 libayatana-ido3-0.4-0 libayatana-indicator3-7
  libbluetooth3 libdbusmenu-glib4 libdbusmenu-gtk3-4 libgcr-ui-3-1
  libmbim-glib4 libmbim-proxy libmm-glib0 libndp0 libnm0 libnma0
  libpam-gnome-keyring libpcap0.8 libqmi-glib5 libqmi-proxy libteamdctl0
  mobile-broadband-provider-info modemmanager notification-daemon p11-kit
  p11-kit-modules pinentry-gnome3 ppp
Suggested packages:
  libteam-utils network-manager-openconnect-gnome
  network-manager-openvpn-gnome network-manager-vpnc-gnome
  network-manager-pptp-gnome pinentry-doc
The following NEW packages will be installed:
  dns-root-data dnsmasq-base gcr gnome-keyring gnome-keyring-pkcs11
  libayatana-appindicator3-1 libayatana-ido3-0.4-0 libayatana-indicator3-7
  libbluetooth3 libdbusmenu-glib4 libdbusmenu-gtk3-4 libgcr-ui-3-1
  libmbim-glib4 libmbim-proxy libmm-glib0 libndp0 libnm0 libnma0
  libpam-gnome-keyring libpcap0.8 libqmi-glib5 libqmi-proxy libteamdctl0
  mobile-broadband-provider-info modemmanager network-manager
  network-manager-gnome notification-daemon p11-kit p11-kit-modules
  pinentry-gnome3 ppp
0 upgraded, 32 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.2 MB of archives.
After this operation, 38.7 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian buster/main armhf libbluetooth3 armhf 5.50-1.2~deb10u1+rpt2 [93.5 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf dnsmasq-base armhf 2.80-1+rpt1+deb10u1 [400 kB]
Get:2 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libmm-glib0 armhf 1.10.0-1 [903 kB]
Get:4 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libndp0 armhf 1.6-1 [9,328 B]
Get:5 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libnm0 armhf 1.14.6-2+deb10u1 [295 kB]
Get:6 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libteamdctl0 armhf 1.28-1 [10.1 kB]
Get:7 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf network-manager armhf 1.14.6-2+deb10u1 [2,136 kB]
Get:8 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf dns-root-data all 2019031302 [5,396 B]
Get:9 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libgcr-ui-3-1 armhf 3.28.1-1 [132 kB]
Get:10 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf gcr armhf 3.28.1-1 [244 kB]
Get:11 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf p11-kit-modules armhf 0.23.15-2+deb10u1 [194 kB]
Get:12 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf p11-kit armhf 0.23.15-2+deb10u1 [252 kB]
Get:13 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf pinentry-gnome3 armhf 1.1.0-2 [61.0 kB]
Get:14 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf gnome-keyring armhf 3.28.2-5 [868 kB]
Get:15 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf gnome-keyring-pkcs11 armhf 3.28.2-5 [306 kB]
Get:16 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libayatana-ido3-0.4-0 armhf 0.4.4-1 [60.8 kB]
Get:17 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libayatana-indicator3-7 armhf 0.6.2-3 [85.5 kB]
Get:18 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libdbusmenu-glib4 armhf 18.10.20180917~bzr490+repack1-1 [50.6 kB]
Get:19 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libdbusmenu-gtk3-4 armhf 18.10.20180917~bzr490+repack1-1 [39.8 kB]
Get:20 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libayatana-appindicator3-1 armhf 0.5.3-4 [81.9 kB]
Get:21 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libmbim-glib4 armhf 1.18.0-1 [142 kB]
Get:22 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libmbim-proxy armhf 1.18.0-1 [70.7 kB]
Get:23 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libnma0 armhf 1.8.20-1.1 [125 kB]
Get:24 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libpam-gnome-keyring armhf 3.28.2-5 [303 kB]
Get:25 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libpcap0.8 armhf 1.8.1-6 [124 kB]
Get:26 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libqmi-glib5 armhf 1.22.0-1.2 [443 kB]
Get:27 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf libqmi-proxy armhf 1.22.0-1.2 [9,032 B]
Get:28 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf mobile-broadband-provider-info all 20170903-1 [54.7 kB]
Get:29 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf modemmanager armhf 1.10.0-1 [1,363 kB]
Get:30 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf network-manager-gnome armhf 1.8.20-1.1 [989 kB]
Get:31 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf notification-daemon armhf 3.20.0-4 [56.3 kB]
Get:32 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf ppp armhf 2.4.7-2+4.1+deb10u1 [312 kB]
Fetched 10.2 MB in 9s (1,077 kB/s)                                             
Extracting templates from packages: 100%
Selecting previously unselected package libbluetooth3:armhf.
(Reading database ... 164289 files and directories currently installed.)
Preparing to unpack .../00-libbluetooth3_5.50-1.2~deb10u1+rpt2_armhf.deb ...
Unpacking libbluetooth3:armhf (5.50-1.2~deb10u1+rpt2) ...
Selecting previously unselected package libmm-glib0:armhf.
Preparing to unpack .../01-libmm-glib0_1.10.0-1_armhf.deb ...
Unpacking libmm-glib0:armhf (1.10.0-1) ...
Selecting previously unselected package libndp0:armhf.
Preparing to unpack .../02-libndp0_1.6-1_armhf.deb ...
Unpacking libndp0:armhf (1.6-1) ...
Selecting previously unselected package libnm0:armhf.
Preparing to unpack .../03-libnm0_1.14.6-2+deb10u1_armhf.deb ...
Unpacking libnm0:armhf (1.14.6-2+deb10u1) ...
Selecting previously unselected package libteamdctl0:armhf.
Preparing to unpack .../04-libteamdctl0_1.28-1_armhf.deb ...
Unpacking libteamdctl0:armhf (1.28-1) ...
Selecting previously unselected package network-manager.
Preparing to unpack .../05-network-manager_1.14.6-2+deb10u1_armhf.deb ...
Unpacking network-manager (1.14.6-2+deb10u1) ...
Selecting previously unselected package dns-root-data.
Preparing to unpack .../06-dns-root-data_2019031302_all.deb ...
Unpacking dns-root-data (2019031302) ...
Selecting previously unselected package dnsmasq-base.
Preparing to unpack .../07-dnsmasq-base_2.80-1+rpt1+deb10u1_armhf.deb ...
Unpacking dnsmasq-base (2.80-1+rpt1+deb10u1) ...
Selecting previously unselected package libgcr-ui-3-1:armhf.
Preparing to unpack .../08-libgcr-ui-3-1_3.28.1-1_armhf.deb ...
Unpacking libgcr-ui-3-1:armhf (3.28.1-1) ...
Selecting previously unselected package gcr.
Preparing to unpack .../09-gcr_3.28.1-1_armhf.deb ...
Unpacking gcr (3.28.1-1) ...
Selecting previously unselected package p11-kit-modules:armhf.
Preparing to unpack .../10-p11-kit-modules_0.23.15-2+deb10u1_armhf.deb ...
Unpacking p11-kit-modules:armhf (0.23.15-2+deb10u1) ...
Selecting previously unselected package p11-kit.
Preparing to unpack .../11-p11-kit_0.23.15-2+deb10u1_armhf.deb ...
Unpacking p11-kit (0.23.15-2+deb10u1) ...
Selecting previously unselected package pinentry-gnome3.
Preparing to unpack .../12-pinentry-gnome3_1.1.0-2_armhf.deb ...
Unpacking pinentry-gnome3 (1.1.0-2) ...
Selecting previously unselected package gnome-keyring.
Preparing to unpack .../13-gnome-keyring_3.28.2-5_armhf.deb ...
Unpacking gnome-keyring (3.28.2-5) ...
Selecting previously unselected package gnome-keyring-pkcs11:armhf.
Preparing to unpack .../14-gnome-keyring-pkcs11_3.28.2-5_armhf.deb ...
Unpacking gnome-keyring-pkcs11:armhf (3.28.2-5) ...
Selecting previously unselected package libayatana-ido3-0.4-0:armhf.
Preparing to unpack .../15-libayatana-ido3-0.4-0_0.4.4-1_armhf.deb ...
Unpacking libayatana-ido3-0.4-0:armhf (0.4.4-1) ...
Selecting previously unselected package libayatana-indicator3-7:armhf.
Preparing to unpack .../16-libayatana-indicator3-7_0.6.2-3_armhf.deb ...
Unpacking libayatana-indicator3-7:armhf (0.6.2-3) ...
Selecting previously unselected package libdbusmenu-glib4:armhf.
Preparing to unpack .../17-libdbusmenu-glib4_18.10.20180917~bzr490+repack1-1_armhf.deb ...
Unpacking libdbusmenu-glib4:armhf (18.10.20180917~bzr490+repack1-1) ...
Selecting previously unselected package libdbusmenu-gtk3-4:armhf.
Preparing to unpack .../18-libdbusmenu-gtk3-4_18.10.20180917~bzr490+repack1-1_armhf.deb ...
Unpacking libdbusmenu-gtk3-4:armhf (18.10.20180917~bzr490+repack1-1) ...
Selecting previously unselected package libayatana-appindicator3-1.
Preparing to unpack .../19-libayatana-appindicator3-1_0.5.3-4_armhf.deb ...
Unpacking libayatana-appindicator3-1 (0.5.3-4) ...
Selecting previously unselected package libmbim-glib4:armhf.
Preparing to unpack .../20-libmbim-glib4_1.18.0-1_armhf.deb ...
Unpacking libmbim-glib4:armhf (1.18.0-1) ...
Selecting previously unselected package libmbim-proxy.
Preparing to unpack .../21-libmbim-proxy_1.18.0-1_armhf.deb ...
Unpacking libmbim-proxy (1.18.0-1) ...
Selecting previously unselected package libnma0:armhf.
Preparing to unpack .../22-libnma0_1.8.20-1.1_armhf.deb ...
Unpacking libnma0:armhf (1.8.20-1.1) ...
Selecting previously unselected package libpam-gnome-keyring:armhf.
Preparing to unpack .../23-libpam-gnome-keyring_3.28.2-5_armhf.deb ...
Unpacking libpam-gnome-keyring:armhf (3.28.2-5) ...
Selecting previously unselected package libpcap0.8:armhf.
Preparing to unpack .../24-libpcap0.8_1.8.1-6_armhf.deb ...
Unpacking libpcap0.8:armhf (1.8.1-6) ...
Selecting previously unselected package libqmi-glib5:armhf.
Preparing to unpack .../25-libqmi-glib5_1.22.0-1.2_armhf.deb ...
Unpacking libqmi-glib5:armhf (1.22.0-1.2) ...
Selecting previously unselected package libqmi-proxy.
Preparing to unpack .../26-libqmi-proxy_1.22.0-1.2_armhf.deb ...
Unpacking libqmi-proxy (1.22.0-1.2) ...
Selecting previously unselected package mobile-broadband-provider-info.
Preparing to unpack .../27-mobile-broadband-provider-info_20170903-1_all.deb ...
Unpacking mobile-broadband-provider-info (20170903-1) ...
Selecting previously unselected package modemmanager.
Preparing to unpack .../28-modemmanager_1.10.0-1_armhf.deb ...
Unpacking modemmanager (1.10.0-1) ...
Selecting previously unselected package network-manager-gnome.
Preparing to unpack .../29-network-manager-gnome_1.8.20-1.1_armhf.deb ...
Unpacking network-manager-gnome (1.8.20-1.1) ...
Selecting previously unselected package notification-daemon.
Preparing to unpack .../30-notification-daemon_3.20.0-4_armhf.deb ...
Unpacking notification-daemon (3.20.0-4) ...
Selecting previously unselected package ppp.
Preparing to unpack .../31-ppp_2.4.7-2+4.1+deb10u1_armhf.deb ...
Unpacking ppp (2.4.7-2+4.1+deb10u1) ...
Setting up libgcr-ui-3-1:armhf (3.28.1-1) ...
Setting up mobile-broadband-provider-info (20170903-1) ...
Setting up libdbusmenu-glib4:armhf (18.10.20180917~bzr490+repack1-1) ...
Setting up dnsmasq-base (2.80-1+rpt1+deb10u1) ...
Setting up libayatana-ido3-0.4-0:armhf (0.4.4-1) ...
Setting up notification-daemon (3.20.0-4) ...
Setting up dns-root-data (2019031302) ...
Setting up gcr (3.28.1-1) ...
Setting up p11-kit-modules:armhf (0.23.15-2+deb10u1) ...
Setting up libpcap0.8:armhf (1.8.1-6) ...
Setting up libteamdctl0:armhf (1.28-1) ...
Setting up libnm0:armhf (1.14.6-2+deb10u1) ...
Setting up ppp (2.4.7-2+4.1+deb10u1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/pppd-dns.service -> /lib/systemd/system/pppd-dns.service.
Setting up gnome-keyring-pkcs11:armhf (3.28.2-5) ...
Setting up libmm-glib0:armhf (1.10.0-1) ...
Setting up libbluetooth3:armhf (5.50-1.2~deb10u1+rpt2) ...
Setting up libndp0:armhf (1.6-1) ...
Setting up p11-kit (0.23.15-2+deb10u1) ...
Setting up libayatana-indicator3-7:armhf (0.6.2-3) ...
Setting up libpam-gnome-keyring:armhf (3.28.2-5) ...
Setting up libmbim-glib4:armhf (1.18.0-1) ...
Setting up libdbusmenu-gtk3-4:armhf (18.10.20180917~bzr490+repack1-1) ...
Setting up libnma0:armhf (1.8.20-1.1) ...
Setting up network-manager (1.14.6-2+deb10u1) ...
Created symlink /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service -> /lib/systemd/system/NetworkManager-dispatcher.service.
Created symlink /etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service -> /lib/systemd/system/NetworkManager-wait-online.service.
Created symlink /etc/systemd/system/multi-user.target.wants/NetworkManager.service -> /lib/systemd/system/NetworkManager.service.
Setting up libmbim-proxy (1.18.0-1) ...
Setting up libayatana-appindicator3-1 (0.5.3-4) ...
Setting up network-manager-gnome (1.8.20-1.1) ...
Setting up libqmi-glib5:armhf (1.22.0-1.2) ...
Setting up libqmi-proxy (1.22.0-1.2) ...
Setting up modemmanager (1.10.0-1) ...
Created symlink /etc/systemd/system/dbus-org.freedesktop.ModemManager1.service -> /lib/systemd/system/ModemManager.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ModemManager.service -> /lib/systemd/system/ModemManager.service.
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for libglib2.0-0:armhf (2.58.3-2+deb10u2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for systemd (241-7~deb10u7+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Setting up pinentry-gnome3 (1.1.0-2) ...
Processing triggers for dbus (1.12.20-0+deb10u1) ...
Processing triggers for shared-mime-info (1.10-1) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Setting up gnome-keyring (3.28.2-5) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  dhcpcd5* openresolv* raspberrypi-net-mods*
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
After this operation, 484 kB disk space will be freed.
(Reading database ... 165406 files and directories currently installed.)
Removing raspberrypi-net-mods (1.3.0) ...
Removing dhcpcd5 (1:8.1.2-1+rpt1) ...
Removing openresolv (3.8.0-1) ...
Processing triggers for man-db (2.8.5-2) ...
(Reading database ... 165361 files and directories currently installed.)
Purging configuration files for dhcpcd5 (1:8.1.2-1+rpt1) ...
Purging configuration files for openresolv (3.8.0-1) ...
Purging configuration files for raspberrypi-net-mods (1.3.0) ...
Processing triggers for systemd (241-7~deb10u7+rpi1) ...
grep: /home/pi/.config/lxpanel/LXDE-pi/panels/panel: No such file or directory

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Setting up Ethernet for both link-local and DHCP
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

IP Address is in correct format, proceeding to set up the static IP
Connection 'Wired DHCP Ethernet' (d37a3f6c-bf6a-4b89-a06c-e7bb0619d50f) successfully added.
Connection 'Link Local Ethernet' (c10c02ea-9bd0-4f59-adc7-fab940935181) successfully added.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Installing RealVNC Server
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Reading package lists... Done
Building dependency tree       
Reading state information... Done
realvnc-vnc-server is already the newest version (6.7.2.42622).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Created symlink /etc/systemd/system/multi-user.target.wants/vncserver-x11-serviced.service -> /lib/systemd/system/vncserver-x11-serviced.service.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Making Utilities Folder with script shortcuts for the Desktop
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Preventing Wifi Power Management from shutting down AdHoc and Hotspot Networks
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Creating raspberrypi_FieldWifi, Hotspot Wifi for the observing field
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Connection 'raspberrypi_FieldWifi' (1fcec576-1b63-4a64-ac28-998ce95e7e7b) successfully added.
Connection 'raspberrypi_FieldWifi_5G' (beba17fd-135e-43b8-bee0-b43fde57417a) successfully added.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Configuring Field wifi to autoconnect after wifi fails
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Verifying that the Pi is still online and able to access all required online resources.  The network configuration may have been changed.  If the Pi no longer has internet connection, you should restart it and reconnect it to the internet.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ZRam-script, (https://raw.githubusercontent.com/novaspirit/rpi_zram/master/zram.sh), a required connection, was not found, aborting script.
If you would like the script to run anyway, please comment out the line that tests this connection in this script.

**Comment by rlancaste** [comment]
So if you look at the very bottom of the output, it looks like the pi didn't have an internet connection later in the run and it aborted.  Did you have an ethernet cable connected the whole time it was running?

**Comment by Dragonball1472** [comment]
No i didn't have

**Comment by rlancaste** [comment]
I would probably recommend that just to make sure that it can continue.

**Comment by evripidis** [comment]
I had the same issue and I was connected via WiFi. I can confirm that as soon as I plugged in the Ethernet, everything worked ok.

**Comment by rlancaste** [comment]
Ok thank you!  I should update the instructions to say to make sure to keep it plugged into Ethernet then.
