### ISSUE TITLE
shortcuts not created on a German system

### ISSUE THREAD

**Issue by dmnkhhn** [rlancaste/AstroPi3#4]
Hello there,

it is not an actual issue but something I ran into:
My Ubuntu is set to German and the folder is named _Schreibtisch_ instead of _Desktop_ so the shortcut creation fails.
The fix is fairly easy: just replace _~/Desktop/_ with _~/Schreibtisch/_ in the shell script and you are all set. It took me a while since on my Mac it is also called _Schreibtisch_ but it is still called _Desktop_ internally.

**Comment by rlancaste** [comment]
Ok, that's interesting

**Comment by rlancaste** [comment]
can you try this command?

xdg-user-dir DESKTOP

**Comment by dmnkhhn** [comment]
```
astropi@astropi:~$ xdg-user-dir DESKTOP
/home/astropi/Schreibtisch
```
