### ISSUE TITLE
Ekos is missing (Armbian Debian on RockPro64)

### ISSUE THREAD

**Issue by dmnkhhn** [rlancaste/AstroPi3#6]
Hello!
Today I have setup my RockPro64 with the Armbian Debian from your Readme (Debian Stretch with Armbian Linux 4.4.182-rockchip64) and ran `sudo ./setupDebianSBC.sh` and it took quite some time to compile Kstars and all the other things.

Much to my surprise Ekos is completely missing from Kstars as if it never existed. 

I'm currently running `sudo ./setupDebianSBC.sh` again and I do see output like this:
```
[  5%] Generating ekosadaptor.cpp, ekosadaptor.h
[  5%] Generating ekosadaptor.moc
```
and
```
[ 20%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/ekos.cpp.o
[ 20%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/manager.cpp.o
[ 20%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/profileeditor.cpp.o
[ 20%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/profilewizard.cpp.o
[ 20%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/qMDNS.cpp.o
[ 21%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/opsekos.cpp.o
[ 21%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/auxiliary/dome.cpp.o
[ 21%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/auxiliary/weather.cpp.o
[ 21%] Building CXX object kstars/CMakeFiles/KStarsLib.dir/ekos/auxiliary/dustcap.cpp.o
```

Have you experienced something like this? I had it running before but that was some time ago with the `setupAstro64.sh` script.

**Comment by rlancaste** [comment]
Did INDI successfully install ahead of KStars?  If KStars doesn’t find INDI, then it doesn’t include it in the build

**Comment by rlancaste** [comment]
Also at the beginning of the KStars build it prints everything it finds and doesn’t find that it might need

**Comment by dmnkhhn** [comment]
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Building and Installing INDI
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Already up-to-date.
``` 
then
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Building and Installing core LibINDI
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
a couple of hundred lines later
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Building and Installing the INDI 3rd Party Libraries
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
here comes the KStars part:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Building and Installing KStars
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Already up-to-date.
-- Could not set up the appstream test. appstreamcli is missing.
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by "KF5NotifyConfig"
  with any of the following names:

    KF5NotifyConfigConfig.cmake
    kf5notifyconfig-config.cmake

  Add the installation prefix of "KF5NotifyConfig" to CMAKE_PREFIX_PATH or
  set "KF5NotifyConfig_DIR" to a directory containing one of the above files.
  If "KF5NotifyConfig" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:127 (find_package)


-- Could NOT find KF5NotifyConfig: found neither KF5NotifyConfigConfig.cmake nor kf5notifyconfig-config.cmake 
-- Could NOT find KF5 (missing:  NotifyConfig) 
-- Found CFITSIO: /usr/lib/aarch64-linux-gnu/libcfitsio.so
-- Found INDI: /usr/lib/aarch64-linux-gnu/libindi.so, /usr/include/libindi
-- Found INDI Client Library: /usr/lib/aarch64-linux-gnu/libindiclient.a
-- Found INDI: /usr/lib/aarch64-linux-gnu/libindiclient.a, /usr/include/libindi
-- Found WCSLIB: /usr/lib/aarch64-linux-gnu/libwcs.so, /usr/include/wcslib
-- Found Xplanet: /usr/bin/xplanet
CMake Warning at CMakeLists.txt:240 (find_package):
  By not providing "FindQt5DataVisualization.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5DataVisualization", but CMake did not find one.

  Could not find a package configuration file provided by
  "Qt5DataVisualization" with any of the following names:

    Qt5DataVisualizationConfig.cmake
    qt5datavisualization-config.cmake

  Add the installation prefix of "Qt5DataVisualization" to CMAKE_PREFIX_PATH
  or set "Qt5DataVisualization_DIR" to a directory containing one of the
  above files.  If "Qt5DataVisualization" provides a separate development
  package or SDK, be sure it has been installed.


-- Found astrometry.net: /usr/bin/solve-field
CMake Warning at CMakeLists.txt:248 (find_package):
  By not providing "FindQt5Keychain.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Keychain", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Keychain" with
  any of the following names:

    Qt5KeychainConfig.cmake
    qt5keychain-config.cmake

  Add the installation prefix of "Qt5Keychain" to CMAKE_PREFIX_PATH or set
  "Qt5Keychain_DIR" to a directory containing one of the above files.  If
  "Qt5Keychain" provides a separate development package or SDK, be sure it
  has been installed.


-- Found NOVA: /usr/lib/aarch64-linux-gnu/libnova.so
-- Found GSL: /usr/include (found version "2.3") 
-- 
-- The following RUNTIME packages have been found:

 * Xplanet , Renders an image of all the major planets and most satellites , <http://xplanet.sourceforge.net>
   Gives KStars support for xplanet.
 * AstrometryNet , Astrometrics Library , <http://www.astrometry.net>
   Support for plate solving in KStars.

-- The following OPTIONAL packages have been found:

 * CFitsio , FITS IO Library , <http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html>
   Support for the FITS (Flexible Image Transport System) data format in KStars.
 * INDI (required version >= 1.7.1) , Astronomical instrumentation control , <http://www.indilib.org>
   Support for controlling astronomical devices on Linux with KStars.
 * LibRaw , Library for reading RAW files , <http://www.libraw.org>
   Support for reading and displaying RAW files in KStars.
 * WCSLIB , World Coordinate System library , <http://www.atnf.csiro.au/people/mcalabre/WCS>
   WCS enables KStars to read and process world coordinate systems in FITS header.
 * OpenGL , Open Graphics Library , <http://www.opengl.org>
   Support for hardware rendering in KStars.
 * PkgConfig

-- The following REQUIRED packages have been found:

 * ECM (required version >= 1.7.0)
 * Qt5Gui
 * Qt5Qml
 * Qt5Quick
 * Qt5Xml
 * Qt5Sql
 * Qt5Widgets (required version >= 5.7.1)
 * Qt5Svg
 * Qt5Network
 * Qt5PrintSupport
 * Qt5Concurrent
 * Qt5WebSockets
 * Qt5 (required version >= 5.4)
 * Qt5Core
 * KF5Auth
 * KF5Config
 * KF5Crash
 * KF5WidgetsAddons
 * KF5NewStuff
 * Gettext
 * PythonInterp
 * KF5I18n
 * KF5KIO
 * KF5XmlGui
 * KF5Plotting
 * KF5Notifications
 * KF5
 * Eigen3
 * ZLIB
 * Threads
 * Nova
 * GSL
 * Qt5Test
 * KF5DocTools

-- The following OPTIONAL packages have not been found:

 * KF5NotifyConfig
 * Qt5DataVisualization
 * Qt5Keychain

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dmnkhhn/AstroRoot/kstars-build
```

**Comment by rlancaste** [comment]
Ok that’s odd, it sounds like it found it just fine.  One thing that I notice though.  It said that the lib directory was /usr/lib/aarch64-linux-gnu/ and not /usr/lib Can you check in that directory and see if it is just INDI stuff in there?

**Comment by rlancaste** [comment]
I am curious if those files should be in /usr/lib

**Comment by rlancaste** [comment]
Also I think I might add those 3 missing packages although that isn’t related

**Comment by rlancaste** [comment]
Did you resolve the issue?  Were the files installed to the wrong lib directory ?   I was having an issue like that with Manjaro.

**Comment by dmnkhhn** [comment]
The second install resolved this issues.
I didn't save the the log from the first install but I suppose it could have helped comparing those.

There was only one difference between the first and the second install: My firewall was blocking the NTP queries and the date of the RockPro64 was way off. I fixed that one first and then tried the second install. `apt` had some certificate warnings before and it might be that it didn't install all things it needed.

Now the bad news:
I had some other major problems with Armbian and my ZWO ASI camera on the USB 3.0 port so I went with the _ayufan-rock64_ packages and Ubuntu Mate in the middle of the night trying to get a running system before daybreak.
The Ubuntu script ran without any problems and I'll be using this for now.

I'm curious to know that caused the problems with the first install but I can't help debug it any further.

**Comment by dmnkhhn** [comment]
Unrelated to this issue but do have an Amazon wishlist or other ways to compensate for your time and effort you are putting into this?

**Comment by rlancaste** [comment]
Thank you very much for the offer!  I don’t have an amazon wish list set up.  That is not a bad idea though.  It would be nice to get some more sbcs and related tech to work on improving the scripts and further development.  I have a couple of Pis, an Odroid C2 and I had a rock64 until last weekend till it seems to have died

**Comment by rlancaste** [comment]
I have been thinking about some others that would be good to test the script and refine it on.  The goal is to have a script that will work on numerous distros and SBCs

**Comment by rlancaste** [comment]
AH I just found the Debian issue!!  Took a couple of hours to find, but basically, there was a line with the kstars dependencies that said to install libindi-dev.  I had effectively installed indi version 1.2 over top of the latest version 1.8 that the script built.

**Comment by rlancaste** [comment]
For your SBC, I am glad to hear that running it again allowed it to work.  It probably worked because it re-installed the new 1.8 version over top of the 1.2 version.  So this should work fine.   But note that it probably thinks libindi-dev is installed.  you might want to remove this package and run the script again, so that libindi doesn't get overwritten in a system update.  The version in the Debian repo is really really old.  I say you might want to remove the package, because Debian is not updated very frequently.  So, it might not be a problem at all because the package won't be updated for ages.
