### ISSUE TITLE
Installing NetworkManager causes wifi dropout and failed install on Raspbian

### ISSUE THREAD

**Issue by mattkellaway** [rlancaste/AstroPi3#8]
Hey! love the scripts - it really makes it a lot easier to have reproducible builds on RPi.

I realise that it's very much to be expected to kill the wifi when doing the install, but the script won't fail and reports success even though kstars and indi have not cloned and everything after the network config has failed.

If you're using ethernet to do the initial install then you'd never notice, but a novice user may not understand what's going on and why nothing got installed, despite the success message.

My method for dealing with this is splitting the script in two, doing the dist-upgrade and network conf, rebooting and then running the software install half. A more robust method might be to check for internet connectivity after the nm install and bomb out asking the user to reconnect to wifi or reboot.

Anyway, thanks for putting in so much time to the project!

**Comment by rlancaste** [comment]
Sorry for the delay on this.  It is a good idea, but I have had a lot of work recently and I haven't had time yet.

**Comment by rlancaste** [comment]
Ok I think I have fixed this now.
