### ISSUE TITLE
kstars not installed

### ISSUE THREAD

**Issue by photorat** [rlancaste/AstroPi3#9]
During the installation I got a fatal error for kstars, the address in line "git clone git://anongit.kde.org/kstars" seems no longer valid. Installing using "git clone https://github.com/KDE/kstars" seems to work (compiling not finished while I report this).

EDIT I edited line 675 with the new address in file setupAstroRaspbianPi.sh, tried it on a fresh installed raspbian. It's work. 

PLS: find the file attached below
[setupAstroRaspbianPi.zip](https://github.com/rlancaste/AstroPi3/files/3747859/setupAstroRaspbianPi.zip)

**Comment by rlancaste** [comment]
Thanks, I will see if there is something wrong with the old link.  It should be the right one I think, but maybe there is an issue.

**Comment by rlancaste** [comment]
Ok I think I have fixed this now.
